apiVersion: v1
items:
- apiVersion: acid.zalan.do/v1
  kind: postgresql
  metadata:
    labels:
      team: seo-wizzard
    name: postgres
    namespace: default
  spec:
    databases:
      shopify_app_db: shopify
    maintenanceWindows: []
    numberOfInstances: 1
    postgresql:
      version: "17"
    patroni:
      pg_hba:
        - local     all          all                        trust
        - host      all          all       127.0.0.1/32     md5
        - hostssl   all          postgres  all              md5
        - host      all          all       ::1/128          md5
        - local     replication  standby                    trust
        - hostssl   replication  standby   all              md5
        - host      all          shopify   all              md5
        - hostnossl all          all       all              reject
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
    teamId: acid
    users:
      shopify:
        - superuser
    volume:
      iops: 3000
      size: 70Gi
      throughput: 125
  status:

kind: List
metadata:
  resourceVersion: ""
