name = "seo-wizzard-extension"
type = "theme"
extension_points = [
  "web.templates.404",
  "web.error.render"
]
[[metafields]]
namespace = "redirect_settings"
key = "default_redirect"
type = "single_line_text_field"
description = "Default URL to redirect to when a page is not found"

[settings]
[[settings.fields]]
key = "enable_logging"
type = "boolean"
name = "Enable 404 Logging"
description = "Log 404 errors for analytics"
default = true

