# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8d735ce17d5961291e4e000dd6ad3ff7"
application_url = "https://meaningful-fig-chief-arbitrary.trycloudflare.com"
embedded = true
name = "seo-wizzard"
handle = "seo-wizzard-7"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://meaningful-fig-chief-arbitrary.trycloudflare.com/auth/callback",
  "https://meaningful-fig-chief-arbitrary.trycloudflare.com/auth/shopify/callback",
  "https://meaningful-fig-chief-arbitrary.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://meaningful-fig-chief-arbitrary.trycloudflare.com"
subpath = "404-redirect"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "baltisilacuri.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
