apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seo-wizzard.fullname" . }}
  labels:
    {{- include "seo-wizzard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seo-wizzard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "seo-wizzard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "seo-wizzard.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort}}"
            - name: SHOPIFY_APP_URL
              value: https://frontend.billing-service.shop
            - name: WEBHOOKS_SERVICE_URL
              value: https://broker.billing-service.shop/webhooks
            - name: SHOPIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: seo-wizzard-secrets
                  key: shopify-api-key
            - name: SHOPIFY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: seo-wizzard-secrets
                  key: shopify-api-secret
            - name: SCOPES
              value: "read_themes"
            - name: ENV
              value: production
            - name: SCYLLA_HOST
              value: simple-cluster-client.scylla.svc.cluster.local
            - name: SCYLLA_DATACENTER
              value: us-east-1
            - name: SCYLLA_KEYSPACE
              value: invoice_buddy
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
